name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      # Your build steps here...
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main  # Use a different branch for deployment
          folder: dist      # The folder with your built files
          clean: false    # Automatically remove deleted files
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}